create table USERS_TABLE
(
    NAME     CHARACTER VARYING(255) not null
        unique,
    PASSWORD CHARACTER VARYING(255) not null,
    ID       BIGINT generated by default as identity
        primary key
);

create table INDICATION_TYPE
(
    ID        BIGINT                not null generated by default as identity,
    TYPE_NAME CHARACTER VARYING(30) not null,
    constraint INDICATION_TYPE_PK
        primary key (ID)
);

create table INDICATION
(
    ID               BIGINT                        not null generated by default as identity,
    INDICATION_VALUE BIGINT                        not null,
    USERNAME         CHARACTER VARYING(255) not null,
    DATE             TIMESTAMP                     not null,
    TYPE             BIGINT                        not null,
    constraint ID
        primary key (ID),
    constraint "INDICATION_INDICATION_TYPE_ID_fk"
        foreign key (INDICATION_VALUE) references INDICATION_TYPE
);