jdbc:
  url: jdbc:postgresql://localhost:5432/monitoring?currentSchema=monitoring-schema
  user: monitor
  password: monitor
logging.level.org.apache.catalina.core: INFO
logging.level.org.apache.catalina.session: INFO